version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --debug --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  lint:
    working_directory: ~/repo
    docker:
      - image: golangci/golangci-lint:v1.42.1
    steps:
      - checkout
      - run:
          name: Lint Repo
          command: |
            golangci-lint run -v

workflows:
  standard:
    jobs:
      - lint
      - test