// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/tjper/rustcron/internal/graph/model"
)

type ChangePasswordInput struct {
	Hash     string `json:"hash"`
	Password string `json:"password"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserResult struct {
	User *User `json:"user"`
}

type ForgotPasswordInput struct {
	Email string `json:"email"`
}

type LoginUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginUserResult struct {
	User *User `json:"user"`
}

type UpdateUserPasswordInput struct {
	ID              string `json:"id"`
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type UpdateUserPasswordResult struct {
	User *User `json:"user"`
}

type User struct {
	ID         string         `json:"id"`
	Email      string         `json:"email"`
	Role       model.RoleKind `json:"role"`
	VerifiedAt *time.Time     `json:"verifiedAt"`
	UpdatedAt  time.Time      `json:"updatedAt"`
	CreatedAt  time.Time      `json:"createdAt"`
}

func (User) IsEntity() {}

type VerifyEmailInput struct {
	Hash string `json:"hash"`
}
