version: "3.8"
services:
  db:
    image: "postgres:13.0"
    restart: "always"
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "password"
    networks:
      - rustpm
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout:  30s
      retries: 5
      start_period: 5s
  redis:
    image: "redis"
    restart: "always"
    ports:
      - "6379"
    networks:
      - rustpm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://redis:6379"]
      interval: 5s
      timeout:  30s
      retries: 5
      start_period: 5s
  payment:
    build:
      context: ".."
      dockerfile: "deploy/Dockerfile.payment"
    restart: "always"
    ports:
      - "8080:8080"
    environment:
      PAYMENT_PORT: "8080"
      PAYMENT_DSN: "host=db user=postgres password=password dbname=postgres port=5432 sslmode=disable TimeZone=UTC"
      PAYMENT_MIGRATIONS: "file:///db/migrations"
      PAYMENT_REDIS_ADDR: "redis:6379"
      PAYMENT_REDIS_PASSWORD: ""
      PAYMENT_STRIPE_KEY: ${STRIPE_KEY}
      PAYMENT_STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    networks:
      - rustpm
    depends_on:
      - db
      - redis
  cronman:
    build:
      context: ".."
      dockerfile: "deploy/Dockerfile.cronman"
    restart: "always"
    ports:
      - "8081:8080"
    environment:
      CRONMAN_PORT: "8080"
      CRONMAN_DSN: "host=db user=postgres password=password dbname=postgres port=5432 sslmode=disable TimeZone=UTC"
      CRONMAN_MIGRATIONS: "file:///db/migrations"
      CRONMAN_REDIS_ADDR: "redis:6379"
      CRONMAN_REDIS_PASSWORD: ""
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - rustpm
    depends_on:
      - db
      - redis
  user:
    build:
      context: ".."
      dockerfile: "deploy/Dockerfile.user"
    restart: "always"
    ports:
      - "8082:8080"
    environment:
      USER_PORT: "8080"
      USER_DSN: "host=db user=postgres password=password dbname=postgres port=5432 sslmode=disable TimeZone=UTC"
      USER_MIGRATIONS: "file:///db/migrations"
      USER_REDIS_ADDR: "redis:6379"
      USER_REDIS_PASSWORD: ""
      USER_MAILGUN_DOMAIN: "mg.rustpm.com"
      USER_MAILGUN_HOST: "http://localhost:8000"
      USER_MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      USER_ADMINS: ${ADMINS}
    networks:
      - rustpm
    depends_on:
      - db
      - redis
networks:
  rustpm:
