version: "3.8"
services:
  db:
    image: "postgres:13.0"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
  redis:
    image: "redis"
    restart: "always"
    ports:
      - "6379:6379"
